# Generated by Django 5.0 on 2023-12-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='Topi_description',
            new_name='topi_description',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='Topic_name',
            new_name='topic_name',
        ),
    ]
