# Generated by Django 5.0 on 2023-12-14 10:34

import audioapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0002_rename_topi_description_topic_topi_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_audio1', models.FileField(upload_to=audioapp.models.audio_file_path)),
                ('con_audio2', models.FileField(upload_to=audioapp.models.audio_file_path)),
                ('con_audio3', models.FileField(upload_to=audioapp.models.audio_file_path)),
                ('con_audio4', models.FileField(upload_to=audioapp.models.audio_file_path)),
                ('con_audio5', models.FileField(upload_to=audioapp.models.audio_file_path)),
                ('con_audio6', models.FileField(upload_to=audioapp.models.audio_file_path)),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='audioapp.topic')),
            ],
        ),
    ]
