# Generated by Django 5.0 on 2023-12-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0003_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='con_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
