# Generated by Django 5.0 on 2023-12-14 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0004_conversation_con_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='folder_number',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='topic_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audioapp.topic'),
        ),
    ]
