# Generated by Django 5.0 on 2023-12-14 11:49

import audioapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0007_alter_topic_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiomodel',
            old_name='audio_file',
            new_name='audio_file1',
        ),
        migrations.AddField(
            model_name='audiomodel',
            name='audio_file2',
            field=models.FileField(default='', upload_to=audioapp.models.audio_file_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiomodel',
            name='audio_file3',
            field=models.FileField(default='', upload_to=audioapp.models.audio_file_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiomodel',
            name='audio_file4',
            field=models.FileField(default='', upload_to=audioapp.models.audio_file_path),
            preserve_default=False,
        ),
    ]
