# Generated by Django 5.0 on 2023-12-14 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0009_remove_topic_description_remove_topic_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='audiofile1',
            new_name='audio_file1',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='audiofile2',
            new_name='audio_file2',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='audiofile3',
            new_name='audio_file3',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='conversation_name',
            new_name='conver_name',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='audiofile4',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='conversation_topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_name',
        ),
        migrations.AddField(
            model_name='conversation',
            name='folder_number',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audioapp.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
